// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechMailGuard.Infrastructure.Persistence;

#nullable disable

namespace TechMailGuard.Infrastructure.Migrations
{
    [DbContext(typeof(TechMailGuardDbContext))]
    partial class TechMailGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechMailGuard.Domain.Aggregates.Mailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.HasKey("Id");

                    b.ToTable("Mailboxes", (string)null);
                });

            modelBuilder.Entity("TechMailGuard.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDetected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MailboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewsletterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SenderEmail");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("TechMailGuard.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("TechMailGuard.Domain.Aggregates.Mailbox", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("MailboxId");
                });

            modelBuilder.Entity("TechMailGuard.Domain.Aggregates.Mailbox", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
