@TechMailGuard.API_HostAddress = http://localhost:5097

### create mailbox
POST {{TechMailGuard.API_HostAddress}}/api/mailbox
Content-Type: application/json

{
  "email": "test@techmailguard.com",
  "provider": "Gmail"
}

### get all mailbox 
GET {{TechMailGuard.API_HostAddress}}/api/mailbox
